# fly.toml app configuration file generated for okkarelatorio on 2025-03-19T13:41:06-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'okkarelatorio'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  DATA_DIR = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[mounts]
  source = "db_volume"
  destination = "/data"
