# Generated by Django 5.1.7 on 2025-03-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='hora',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='hora_modificada',
            field=models.IntegerField(default=0),
        ),
    ]
