# Generated by Django 5.1.7 on 2025-03-25 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_relatorio_hora_relatorio_hora_modificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='diretor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_diretor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='hora',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='setor',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('comunicacao', 'Comunicação'), ('marketing', 'Marketing')], default='administrativo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
